### ISSUE TITLE
Flask 2.0.1 incompatibility with g2p

### ISSUE THREAD

**Issue by joanise** [roedoejet/g2p#111]
Well, I guess we should have said `Flask==2.0.0`, not `Flask>=2.0.0`.
Turns out we're not compatible with 2.0.1 - see https://travis-ci.com/github/roedoejet/g2p/builds/227010018

A possible patch is to change `g2p/api.py` line 128, where the problem occurs, to read

    g2p_api = Blueprint('resources_g2p', __name__)

instead of 

    g2p_api = Blueprint('resources.g2p', __name__)

The issue is that with 2.0.1, Blueprint raises ValueError if `"." in name`.

But I don't know what impact there could be from changing that resource name. The g2p unit tests still pass, but is there a potential impact on convertextract or something else?

**Comment by roedoejet** [comment]
I really don't understand why this was added. I can see it being added as a warning but throwing an error? Strange. We can either fix 2.0.0 or just change to `resources-g2p` (I would prefer hyphens because underlines make it look like a method to me)

**Comment by joanise** [comment]
Does nothing depend on this name elsewhere?

**Comment by joanise** [comment]
I'm happy with `resources-g2p`, that's fine by me.

**Comment by roedoejet** [comment]
> Does nothing depend on this name elsewhere?

it shouldn't. it's just the name of the resource blueprint
