### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by roedoejet** [roedoejet/g2p#13]
We need to write documentation to make this useable. There are also some standards that we need to include:

For example, folder names in `/g2p/mappings/langs` should use languages' ISO639-2 Terminology codes (as opposed to Bibliography codes). This is not at all obvious without documentation.

**Comment by littell** [comment]
I think they should be ISO639-3, actually; a lot of these languages don't have ISO639-2 codes if I remember correctly.

**Comment by roedoejet** [comment]
Noted! I think for most of the languages we have ISO639-2 is equivalent to ISO639-3 but I'll look into that and double check.

**Comment by joanise** [comment]
Pat: good idea to go with 639-3. I was not even aware that standard existed! It's mostly consistent with 639-2, fortunately.
If you're not familiar with it, this site lists 639-1, -2 (B and T), -3, and -5 codes: https://iso639-3.sil.org/code_tables/639/data, as well as the history of each code, e.g., https://iso639-3.sil.org/code/fra

**Comment by roedoejet** [comment]
From @joanise in reference to https://github.com/roedoejet/g2p/issues/15

> I've reviewed this code, and I can see that it works for the cases we need, but it has some limitations that might be worth documenting.
I'm impressed with how well it works, as I had to try pretty hard to trip it. It handles (a|(e|o)) correctly (equivalent to [aeo]), but I was able to trip it with (a(e|o)), which is equivalent to ae|ao.
This is a perfectly reasonable limitation - supporting [...] and ...|... is important, while I think supporting things like a(e|o) is not,

**Comment by littell** [comment]
Also, for script names (e.g. Roman vs. Syllabics) we should probably use ISO 15924 terminology where possible.  That keeps us closer to IETF BCP 47 practices.  (I don't think we really need to adopt BCP 47, because a lot of what we're concerned with is finer-grained than that, but using a common vocab is good.)

**Comment by roedoejet** [comment]
Ok, so instead of `iku-sro`, it would be `iku-Latn`? I think you did that in one of the repos and I changed it, oops! I think the capital bothered me and I didn't know it was a standard. I'm happy to adopt this though.

**Comment by roedoejet** [comment]
Closed with 823672d
