### ISSUE TITLE
The last five lines in fn-unicode-font mapping don't seem to work on Windows

### ISSUE THREAD

**Issue by joanise** [roedoejet/g2p#130]
g2p convert 'X   ล ɤ ∛ X' fn-unicode-font fn-unicode

where the input starts and ends with ascii X, and has the literal character on the left-hand side of each of the last five rules in `font-encodings/fn_unicode.csv` in between.

Run on Windows, this command outputs this line, where each ? is really a literal \x3f in the output:

    x ? ? ? ? ? x

Run on Linux, this command produces the expected output:

    x ᶿ √ ḥ ɣ · x

**Comment by roedoejet** [comment]
This is an issue with your command prompt not being able to render the characters, since the fn_unicode tests pass on windows in CI. I'm going to close this since I don't think there's anything to do apart from updating your terminal to be able to produce those characters.

**Comment by joanise** [comment]
Agreed, this is a terminal bug, not a g2p bug, as proved by #278, which passes on my machine as in the Windows CI.
