### ISSUE TITLE
Abbreviation names cannot be substrings

### ISSUE THREAD

**Issue by joanise** [roedoejet/g2p#133]
If I create a mapping with abbreviations, and use names that are substrings of each other, it breaks the interpretation.

To reproduce, modify `mappings/langs/fra/fra_abbs.csv` and rename `AOU_VOW` to `AOU_VOWEL` and `IE_VOW` to `EI_VOWEL`. Make the corresponding changes in `fra_to_ipa.csv`, run `g2p update`, then `tests/test_langs.py` now fails.

Running `g2p convert --debugger mangeons fra fra-ipa` shows that `AOU_VOWEL` was expanded to `AOU_{value of VOWEL}` instead of `{value of AOU_VOWEL}`.

**Comment by roedoejet** [comment]
I think this means we ought to sort the variable names from longest to shortest and expand them in that order.

**Comment by joanise** [comment]
Yeah, that's probably the simplest solution. Sounds easy to patch.
