### ISSUE TITLE
Certain rules eating characters!

### ISSUE THREAD

**Issue by roedoejet** [roedoejet/g2p#15]
It seems that when `context_before` includes a regex set, it eats that character.

So, a rule with `a,b,c,` and input `ca` is accurately producing `cb`, but a rule with `a,b,[cd],` and the same input is just producing `b`.

**Comment by roedoejet** [comment]
The issue was related to something else. Python must have fixed-width lookbehinds, so G2P will try and interpret the `context_before` value and separate it out into a number of lookbehinds. So if you set `context_before` equal to `a|bc` for example it would turn that into `a|b|c`. It wasn't matching the `[]` set notation though, and as a result it was producing `[((?<=cd))]` instead of `((?<=[cd]))` which when compiled with `a` was matching `ca` and not even being compiled as a lookbehind at all! 

For writing rules, we can get around this easily without changing the code by writing `c|d` instead of `[cd]`. I also modified the functions below to pick up square brackets, but there will likely be other cases where a regex character isn't matched and it breaks the lookbehind.

What do you think @joanise? Let's talk next week about this.

Before:

```
def create_fixed_width_lookbehind(pattern):
    '''Turn all characters into fixed width lookbehinds
    '''
    return re.sub(re.compile(r"""(?<=\(?)[\p{L}\p{M}|]+(?=\)?)""", re.U),
                  pattern_to_fixed_width_lookbehinds, pattern)
```

Supporting square brackets:
```
def create_fixed_width_lookbehind(pattern):
    '''Turn all characters into fixed width lookbehinds
    '''
    return re.sub(re.compile(r"""(?<=\(?)[\[\]\p{L}\p{M}|]+(?=\)?)""", re.U),
                  pattern_to_fixed_width_lookbehinds, pattern)
```

```
def pattern_to_fixed_width_lookbehinds(match):
    ''' Python must have fixed-width lookbehinds.
    '''
    pattern = match.group()
    pattern = sorted(pattern.split('|'), key=len, reverse=True)
    current_len = len(pattern[0])
    all_lookbehinds = []
    current_list = []
    for item in pattern:
        if len(item) == current_len:
            current_list.append(item)
        else:
            current_len = len(item)
            all_lookbehinds.append(current_list)
            current_list = [item]
        if pattern.index(item) == len(pattern) - 1:
            all_lookbehinds.append(current_list)
    all_lookbehinds = [f"(?<={'|'.join(items)})" for items in all_lookbehinds]
    return '(' + '|'.join(all_lookbehinds) + ')'
```

**Comment by roedoejet** [comment]
I realized that regex was getting pretty unreadable, so here's the update with VERBOSE flag:

```
def create_fixed_width_lookbehind(pattern):
    '''Turn all characters into fixed width lookbehinds
    '''
    return re.sub(re.compile(r"""
    (?<=\(?)            # lookbehind
    [\[\]\p{L}\p{M}|]+  # match any number of Unicode characters and diacritics, plus square brackets
    (?=\)?)             # lookahead
    """, re.U | re.VERBOSE),
                  pattern_to_fixed_width_lookbehinds, pattern)
```

**Comment by joanise** [comment]
I've reviewed this code, and I can see that it works for the cases we need, but it has some limitations that might be worth documenting.
I'm impressed with how well it works, as I had to try pretty hard to trip it. It handles `(a|(e|o))` correctly (equivalent to `[aeo]`), but I was able to trip it with `(a(e|o))`, which is equivalent to `ae|ao`.
This is a perfectly reasonable limitation - supporting `[...]` and `...|...` is important, while I think supporting things like `a(e|o)` is not,

**Comment by joanise** [comment]
Another limitation: I tried to say "word-initial" by setting context_before=`\b`, but that doesn't work.
This message comes up in the trace when I try:
```
  File "/gpfs/fs1/nrc/ict/others/u/joa125/sandboxes/readalong/g2p/g2p/mappings/__init__.py", line 179, in rule_to_regex
    Do you have un-escaped regex characters in your input {inp}, contexts {before}, {after}?')
KeyError: 'in_lang'
```

Fix that solves this case: use `[\\\[\]\p{L}\p{M}|]+`, i.e., add `\\` to `[\[\]\p{L}\p{M}|]+`. I don't think it introduces too many unintended consequences.

I don't know if word-initial in an important use case, but it seems worth supporting, unlike `a(e|o)` above.

**Comment by joanise** [comment]
Cool! I just realized I can shutdown and restart the g2p Studio server and keep my browser up - it just reconnects to the new one with my SW patches applied. Sweet. I thought I had to reload and reenter my mappings when I restarted the server.

**Comment by roedoejet** [comment]
Thanks for this @joanise! I agree that I think word-initial (and other regex special characters) are worth supporting. I'll add the quirk around regex composition to the documentation issue.

**Comment by roedoejet** [comment]
> Cool! I just realized I can shutdown and restart the g2p Studio server and keep my browser up - it just reconnects to the new one with my SW patches applied. Sweet. I thought I had to reload and reenter my mappings when I restarted the server.

Yes! I think now so long as you're starting the studio on the same port, it should ping for it even after it's been disconnected, which is more helpful than the previous system which just silently disconnected sometimes :grin:
