### ISSUE TITLE
Dummy mapping generation expects str-equiv-ipa

### ISSUE THREAD

**Issue by roedoejet** [roedoejet/g2p#155]
When running `g2p generate-mapping --dummy str-equiv`

I get the error:

Error: Invalid value for 'IN_LANG' / 'OUT_LANG': Cannot find IPA mapping from "str-equiv" to "str-equiv-ipa": 
There is no mapping between the languages "str-equiv" and "str-equiv-ipa",

there should be some way of handling this without having to temporarily change `str-ipa` to `str-equiv-ipa`

**Comment by joanise** [comment]
Have you tried `g2p generate-mapping --dummy str-equiv str-ipa`?

**Comment by joanise** [comment]
That's what the extra `out_lang` parameter is for, to handle this very case.

**Comment by roedoejet** [comment]
ah right - forgot about that
