### ISSUE TITLE
und does not work correctly in g2p Studio

### ISSUE THREAD

**Issue by joanise** [roedoejet/g2p#165]
In CLI:

```
$ g2p convert éçà und eng-arpabet
EY CH AA
```

In g2p Studio, select:
 - Input language = `und`
 - Output language = `eng-arpabet`
 - Input text = `éçà`

The output shown is `éCH ̧à` instead of `EY CH AA`

Using `eca` as input, the CLI correctly outputs the same `EY CC AA`, but the g2p Studio outputs the also incorrect `eCH a`.

**Comment by joanise** [comment]
@roedoejet You up for taking this issue on?

**Comment by roedoejet** [comment]
the issue seems to be that the studio doesn't have a way of running the und -> und-ascii conversion because it's not a mapping.

**Comment by joanise** [comment]
As far as I can tell the API goes though `make_g2p` and calls `tg = transducer(text)`, so why would that not work???

Oh, wait a second, I'm looking at the wrong source file. It's `convert()` in `app.py` I should look at... and `static/custom.js`. I think I found the problem: this code does not carry the `unidecode` setting from und's config into `kwargs`, so it fails to trigger the unidecode application in `Transducer`.

**Comment by joanise** [comment]
Possible solution: [dev.issue-165](https://github.com/roedoejet/g2p/tree/dev.issue-165)?

The problem is that for unidecode to get invoked, we need `"type": "unidecode"` in `kwargs`. So... I just added it to the js, and it works. Better yet would be to hide that parameter, but I'm not sure how to do that.
