### ISSUE TITLE
Morpheme-break non-voicing is not accounted for in csv rules

### ISSUE THREAD

**Issue by finguist** [roedoejet/g2p#2]
In order to achieve greater accuracy with voicing, the csv rules would need to account for morpheme breaks. Voicing does not occur when a morpheme-initial stop is preceded by a vowel, while all other incidences of stops preceded by vowels are voiced. 

Current csv rule:
t,d,a|ʌ|æ|e|ɛ|ɪ|ɨ|i|ɔ|o|u

Outputs a voiced stop every time a vowel precedes a stop.

A rule that accounts for the morpheme break would be needed to block voicing.

**Comment by roedoejet** [comment]
I think this is a "won't fix". G2P is really just for character based transformations so unless there is a character that marks morpheme boundaries (and so then can be expressed as a G2P rule anyways), I'm not planning on building in any morphologically aware component. The variation across all types of languages would exceed the scope of this project I think.

Thought, the Gitksan data you have been using does mark morpheme boundaries with `-` (affix), `=` (clitic), or `~` (redup) in every line other than the translation and orthographic lines. So you could actually write morphologically aware rules for Gitksan.
