### ISSUE TITLE
Construction interfaces for Mappings

### ISSUE THREAD

**Issue by littell** [roedoejet/g2p#20]
I'm attempting to create a transducer (in this case, Inuktitut SRO to IPA) but the method in the README doesn't seem to work.  I checked the source and the Mapping constructor does not appear to do anything with a "language" kwarg.

The interface in which you go mapping="<filename>" initially appears to work [1], but there's no means to specify the mapping index through this interface, and in this case it's the third.  

The interface in which you specify an in_lang and out_lang loads the mapping, but then the transducer I made from it just leaves everything intact.

[1] Actually, first it needed a fix where we specify the encoding kwarg of open() to "utf-8", since that's a platform-dependent default rather than a cross-platform default.  Python 3.6 and 3.7 on Windows lag behind for some reason on updating open() to a UTF default.

**Comment by roedoejet** [comment]
Sorry, the README was a little out of date. I updated it, and added `encoding='utf8'` to every `open` call. 

Basically, what we do now is just `transducer = make_g2p('iku-sro', 'iku-sro-ipa')` and then you can just call it `transducer('hello world')`. Note if you're editing the mappings, you have to run `g2p update` afterwards.
