### ISSUE TITLE
use the endonym for moh language name?

### ISSUE THREAD

**Issue by joanise** [roedoejet/g2p#208]
For `moh`, we should probably update the config to use the endonym `Kanyen'kehà:ka` as the language name, instead of Mohawk. Or maybe `Kanyen'kehà:ka (Mohawk)`?

**Comment by roedoejet** [comment]
Yes, although Kanyen'kehà:ka is the name of the people, not language. It should be Kanyen'kéha or Kanien'kéha depending on dialect. The problem with endonyms is there are dialect differences that we would either need to choose from or list extensionally. I agree this would be the right thing to do though.

**Comment by dhdaines** [comment]
Yeah, though of course if different dialects have different orthographies then they are de facto different "languages" for our purposes!
