### ISSUE TITLE
Look into reqs.txt that is dependent on the Python version

### ISSUE THREAD

**Issue by joanise** [roedoejet/g2p#221]
We are stuck with vulnerable Werkzeug 2.0.3, which is not actually dangerous because it's dev only, not prod.

It would be useful to have a reqs.txt for Python 3.6, which we want to keep supporting, and a different reqs.txt for >= 3.7 with more current dependencies.

**Comment by dhdaines** [comment]
Note that it also just doesn't work on Python 3.10, see #230

**Comment by roedoejet** [comment]
fixed by https://github.com/roedoejet/g2p/commit/6e6814045b6f04e8eae5e0e9d2281cad5e9f60e9
