### ISSUE TITLE
g2p update needs to be run twice when there are network changes

### ISSUE THREAD

**Issue by joanise** [roedoejet/g2p#237]
Steps to reproduce, simulate removing some mappings:

 - `g2p update`
 - `rm -r g2p/mappings/langs/fra`
 - `g2p update`  -> `g2p/mappings/langs/langs.pkl` and `g2p/mappings/langs/network.pkl` are modified
 - `g2p update` -> `g2p/static/languages-network.json` and `g2p/static/swagger.json` are also modified

Add simulate adding some new mappings (starting from the results of the above steps):

 - `git checkout g2p/mappings/langs/fra`
 - `g2p update` -> `g2p/mappings/langs/langs.pkl` and `g2p/mappings/langs/network.pkl` are modified back 
 - `g2p update` -> `g2p/static/languages-network.json` and `g2p/static/swagger.json` are also modified back

What it looks like is as if `status/*.json` was updated first, from the existing `langs/*.pkl`, then `langs/*.pkl` get updated from the mappings in `langs/*/config*`.

**Comment by joanise** [comment]
Working on this now. I found out some interesting things.

1) When we update the langs and language network to write the .pkl files in `cache_langs()`, we actually just do it in local variables in the function and save to disk, but we don't try to update LANGS and LANGS_NETWORK.

That called for an obvious solution, which led me to noticing that

2) When you import a variable from a module and later modify it in the module, you don't (always) see that update where you imported it.

    - with `from g2p.mappings.langs import LANGS`, if `LANGS` is later reassigned (rather than mutated) during a reload you still see the old value in the other modules where you imported it.
    - with `import g2p.mappings.langs` saying `g2p.mappings.langs.LANGS` does see all changes, whether the original LANGS is mutated or reassigned.

My fixes in progress:
 - update LANGS and LANGS_NETWORK after (or in?) `cache_langs()`,
 - use `import g2p.mappings.langs as G2PLangs` and then `G2PLangs.LANGS` instead of our current method.

PR to come when this is complete and tested.

**Comment by dhdaines** [comment]
Oh, yes, this makes perfect sense, because `import` just creates a reference to whatever you tell it to create a reference to.  So if you `import LANGS` and then reassign `LANGS` you don't have the same reference, whereas if you import `langs` and change `langs.LANGS` then you have changed the attribute `LANGS` on the module `langs`.
