### ISSUE TITLE
"KeyError: 5" when doing g2p on French branch

### ISSUE THREAD

**Issue by joanise** [roedoejet/g2p#24]
When running
```
g2p convert "manger" fra eng-ipa --debugger
```
in my dev branch, I get a "KeyError: 5" exception. See trace log:

```
Traceback (most recent call last):
  File "/home/joa125/u/anaconda3/envs/ilt/bin/g2p", line 11, in <module>
    load_entry_point('g2p', 'console_scripts', 'g2p')()
  File "/home/joa125/u/anaconda3/envs/ilt/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/joa125/u/anaconda3/envs/ilt/lib/python3.7/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/joa125/u/anaconda3/envs/ilt/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/joa125/u/anaconda3/envs/ilt/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/joa125/u/anaconda3/envs/ilt/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/joa125/u/anaconda3/envs/ilt/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/joa125/u/anaconda3/envs/ilt/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/joa125/u/anaconda3/envs/ilt/lib/python3.7/site-packages/flask/cli.py", line 412, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/joa125/u/anaconda3/envs/ilt/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/gpfs/fs1/nrc/ict/others/u/joa125/sandboxes/readalong/g2p-fra/g2p/cli.py", line 74, in convert
    PRINTER.pprint(transducer(input_text, index=index, debugger=debugger))
  File "/gpfs/fs1/nrc/ict/others/u/joa125/sandboxes/readalong/g2p-fra/g2p/transducer/__init__.py", line 475, in __call__
    return self.apply_rules(to_convert, index, debugger)
  File "/gpfs/fs1/nrc/ict/others/u/joa125/sandboxes/readalong/g2p-fra/g2p/transducer/__init__.py", line 482, in apply_rules
    response = transducer(converted, index, debugger)
  File "/gpfs/fs1/nrc/ict/others/u/joa125/sandboxes/readalong/g2p-fra/g2p/transducer/__init__.py", line 72, in __call__
    return self.apply_rules(to_convert, index, debugger)
  File "/gpfs/fs1/nrc/ict/others/u/joa125/sandboxes/readalong/g2p-fra/g2p/transducer/__init__.py", line 371, in apply_rules
    if indices[k]['input_string'] != new_index[k]['input_string'] and len(intermediate_to_convert) - 1 >= k and new_index[k]['input_string'] == intermediate_to_convert[k]:
KeyError: 5
```

Will push a dev branch to my fork shortly.

**Comment by joanise** [comment]
Reference branch on my fork: https://github.com/joanise/g2p branch dev.issue24.
Please do not merge this branch, its history is very messy. But its state is the same as master on roedoejet/g2p plus my French g2p mapping. You can troubleshoot and do the fix on my fork/branch but then apply the fix on your master.

**Comment by joanise** [comment]
Note: the problem does not occur when mapping from fra to fra-ipa, only when going from fra to eng-ipa. The input text is not relevant, I get the same error regardless of text to convert.

**Comment by joanise** [comment]
PS: this worked on my branch before merging in the latest master, but it did not pretty print. I wanted to merge master in to get the benefit of pretty printing but that broke convert instead.

**Comment by roedoejet** [comment]
Ok thanks, I'll have a look shortly!

**Comment by joanise** [comment]
Thanks.
For what it's worth, a number of tests no longer pass in `master`, which could be related. Run `python run.py all` in `g2p/tests` to see several tests fail that passed on the Jan 15 state of `master`.

**Comment by roedoejet** [comment]
OK, I found the bug. It actually didn't need any change from the code (yet), but there's an extra line in your csv file that created a completely blank mapping in both the `fra -> fra-ipa` and `fra-ipa to eng-ipa` generated mapping. If you remove the last line from the csv and either re-generate or remove the empty rule (see below, it's the first rule), then you should get `mɑ̃ʒeː` as the output form, and all the pretty printing as well. This brings up a good point though - we should prevent the Mapping object from allowing rules with empty inputs. Minimally, a rule must have an input.

```json
    {
        "in": "",
        "out": ""
    }
```

**Comment by roedoejet** [comment]
Oh also, feel free to start your own branch on this repo instead of using your fork. You have push permissions right?

**Comment by roedoejet** [comment]
> For what it's worth, a number of tests no longer pass in master, which could be related. Run python run.py all in g2p/tests to see several tests fail that passed on the Jan 15 state of master.

Yes, the TestSuite I'm using (and that Travis is running) is the "dev" suite. So, `python run.py dev`. Running the "all" suite will just use the `unittest.TestLoader.discover` method which is finding a number of un-finished tests, most of which were brought over from RAS. That's a good point though, they need to be cleaned up. Until then, feel free to run the "dev" suite.

**Comment by roedoejet** [comment]
This should be fixed as of d245b442de3d0d995341f1ffac0495fac87dc191

**Comment by joanise** [comment]
So, I don't understand what generated the empty rule. I don't see anything in my own rules that could cause that. Do you mean the newline character on the last line? This is an annoying difference between MacOS and Linux: on Linux, the last line ends with a newline character, which means every non-empty text file has a `\n` as its last character, which does not introduce another line, only (redundantly) marks the end of the last line. On MacOS, judging by the fact that all your files don't have that newline on the last line, I'm guessing the end-of-file alone marks the end of the last line, which means you would see a blank line where I don't. And, unfortunately, it's not straight-forward in Linux to remove that final newline character. When you say "If you remove the last line from the csv", that's something I can figure out how to do, but is really not straightforward.

In reading input text files, it would be a good idea to treat a final empty line as if it was not there, if you don't already do that. In fact, would it be hard to ignore any empty line along the whole file? Feature creep: even nicer, ignore lines that start with `#` as comments, so we could insert comments within the `.csv` file. Yeah, I know, that's not really CSV anymore, but it would be convenient...

**Comment by joanise** [comment]
> Oh also, feel free to start your own branch on this repo instead of using your fork. You have push permissions right?

Yes, I have a `dev.fra` branch on your repo,  but I prefer to use my own fork for throw-away stuff. Right now, I'm creating crazy commits trees that I don't want to preserve. Now that things work again, I should be able to push my `fra` work to dev.fra, merge `master` into it and either send you a pull request or push the merge myself (I think I have permissions to do either).

**Comment by roedoejet** [comment]
> Do you mean the newline character on the last line? This is an annoying difference between MacOS and Linux: on Linux, the last line ends with a newline character, which means every non-empty text file has a \n as its last character, which does not introduce another line, only (redundantly) marks the end of the last line. On MacOS, judging by the fact that all your files don't have that newline on the last line, I'm guessing the end-of-file alone marks the end of the last line, which means you would see a blank line where I don't. And, unfortunately, it's not straight-forward in Linux to remove that final newline character. When you say "If you remove the last line from the csv", that's something I can figure out how to do, but is really not straightforward.

Interesting! I didn't know that. That must be what is causing the empty rule.

> In reading input text files, it would be a good idea to treat a final empty line as if it was not there, if you don't already do that. In fact, would it be hard to ignore any empty line along the whole file?

Yes we could do that. In the meantime, I added a change the just throws away any rule that doesn't have an input. That will solve this problem and others like it, but we could also throw away all new lines when we read in the file.

> Feature creep: even nicer, ignore lines that start with # as comments, so we could insert comments within the .csv file. Yeah, I know, that's not really CSV anymore, but it would be convenient...

I agree this would be nice, but then we would basically be saying that you couldn't have an input of `#`. I think I'd be more of a fan of supporting a format like yaml or toml for writing rules than having some adhoc csv reading syntax. I agree it's a pain to not be able to add comments.

**Comment by joanise** [comment]
Thanks for the bug fix, by the way. My clean `dev.fra` branch is now pushed to your Git repo, and I suggest merging it into master to make `fra` a supported language.

**Comment by roedoejet** [comment]
> Thanks for the bug fix, by the way. My clean dev.fra branch is now pushed to your Git repo, and I suggest merging it into master to make fra a supported language.

Thanks! This is done now.
