### ISSUE TITLE
Add "preserve_case" options to g2p mappings

### ISSUE THREAD

**Issue by joanise** [roedoejet/g2p#270]
#269 implements case preservation for kwk BOAS -> Umista by listing all the case possibilities. This is ugly!

Instead, we should have an option `preserve_case` (Boolean, default: false) which, when true:
 - causes `case_sensitive` to be ignored (or to issue a warning/error when it is false, or even just explicitly set?)
 - the input should be lower-cased, mapped with the mapping's rules following the current `case_sensitive: false` logic, and then
 - we apply these rules, token by token, by looking at the case of the original input:
   - ALLCAPS -> ALLCAPS
   - alllower -> alllower
   - Capitalized -> Capitalized (ideally over tokens, rather than as individual characters are mapped)
   - MiXeDcApS -> ??? maybe in this case applied rule-by-rule in the mapping?
 - Special cases to handle cleanly:
   - small caps like `ɴʜʟᴇɶ` need to be spotted as "no case information" and considered not to break all caps/all lower/capitalized when the rest of the token follows that
   - ditto any other character that does not have casing variants, like `ɘ`, which suggests that the right rule is to test whether a character is case-invariant or not. That information is in the unicode data and easily programmatically available.

**Comment by roedoejet** [comment]
@joanise should this be closed since #274 was merged?

**Comment by joanise** [comment]
Yes, we can close this, finally!
