### ISSUE TITLE
Bug in str

### ISSUE THREAD

**Issue by roedoejet** [roedoejet/g2p#317]
Tim Geng noticed that some of the SENĆOŦEN text has a space followed by U+0327 - the combining cedilla, instead of U+00B8 the standalone cedilla. We should add a rule: \u0020\u0327 -> \u00B8 in the str equiv mapping.

**Comment by joanise** [comment]
That should be easy to add. It's in the spirit of accepting variants found in real text, and there's no ambiguity.

However, str-equiv currently maps U+00B8 to `,`, the ASCII comma, so that what `\u0020\u0327` should also get mapped to.

**Comment by joanise** [comment]
> The community orthography recently solidified the cedilla as the correct variant though, so this rule should also be updated. Unfortunately we can't just do `,` -> U+00B8 because there are legitimate punctuation uses of comma. I'm not really sure how equiv should handle this.

Hmm, that's an altogether new bug, and a much more difficult one to solve: currently commas get mapped to the glottal stop, if you say they're sometimes used as punctuation, we have a problem with the parser (where are token boundaries) and disambiguation (gah!). Statistical models could do this, but not in g2p.

**Comment by joanise** [comment]
Review #318 now, and make a separate issue if you want to change the comma vs small glottal.
