### ISSUE TITLE
Review the user manual to make sure it's consistent with 2.0

### ISSUE THREAD

**Issue by joanise** [roedoejet/g2p#327]
Just do a consistency check on https://roedoejet.github.io/g2p/latest/

**Comment by roedoejet** [comment]
The docs look OK to me, but the following blog posts need to be updated:

- https://blog.mothertongues.org/g2p-basic-mappings-local/
- https://blog.mothertongues.org/g2p-advanced-mappings/
- https://blog.mothertongues.org/g2p-case-feeding/

**Comment by joanise** [comment]
Results of my review so far:
 - https://roedoejet.github.io/g2p/latest/studio/ has an outdated animated screen capture, and only mentions 4 of the 9 options we now support on https://g2p-studio.herokuapp.com/
 - the screen capture for [custom rules](https://roedoejet.github.io/g2p/latest/studio/#custom-rules) is missing the new Prevent Feeding column
 - the [custom abbreviations](https://roedoejet.github.io/g2p/latest/studio/#custom-rules) screen capture is in a different style than the current one, though it's not missing any features.

**Comment by joanise** [comment]
Plus #330

**Comment by joanise** [comment]
#332 and #333 together will complete the fixes to the manual.
There will just remain the fixes to the blog post.
