### ISSUE TITLE
since we use mike for the user manual now, we should be able to have multiple versions published

### ISSUE THREAD

**Issue by joanise** [roedoejet/g2p#328]
right now https://roedoejet.github.io/g2p/latest only has `latest`, but `mike deploy` has options to enable having multiple versions. Once 2.0 is published, it should be called that, and we should be ready to keep labelled versions of the documentation for each future version on PyPI.

**Comment by roedoejet** [comment]
we already do this 🥳 https://github.com/roedoejet/g2p/blob/08f8b1a2e2f56d3755736a8033d73a23af68fbbd/.github/workflows/pythonpublish.yml#L66
