### ISSUE TITLE
Replace lower-casing of expressions with exclusive use of RE case insensitive flag

### ISSUE THREAD

**Issue by roedoejet** [roedoejet/g2p#33]
As for `case_sensitive` by rule, I don't like it. `\S` is not a letter, it's an RE symbol. And when I say match "s" after "\S", I still want "s" to be case insensitive. I believe it is accurate to claim that you only need to protect one letter after each backslash, I'm not aware of any other use of letters in REs that we could want to protect. Actually, why don't you use `re.match`'s own case insensitive option instead of lower-casing the expression?

_Originally posted by @joanise in https://github.com/roedoejet/g2p/issues/31#issuecomment-611618222_

**Comment by roedoejet** [comment]
f93b5a8

**Comment by joanise** [comment]
Cool, my rule with context_before='\S' now works as it should.
