### ISSUE TITLE
Update the blog post for g2p 2.0

### ISSUE THREAD

**Issue by joanise** [roedoejet/g2p#337]
The following blog posts need to be updated:

 - https://blog.mothertongues.org/g2p-basic-mappings-local/
 - https://blog.mothertongues.org/g2p-advanced-mappings/
 - https://blog.mothertongues.org/g2p-case-feeding/

(Task spliced out of #327 comments.)

**Comment by roedoejet** [comment]
Hah! I already did this 😎 https://github.com/MotherTongues/mothertongues-blog/commit/2a3994333bffc2e88697b06792a32cc51bfc0362

It's already in review, it just needs to be merged in to the `publish` branch

**Comment by joanise** [comment]
Sweet, that's an easy one to wrap up then!
