### ISSUE TITLE
CRL mapping needs normalization

### ISSUE THREAD

**Issue by roedoejet** [roedoejet/g2p#34]
Here's my description from the crl mapping readme in `dev.crl` - Can somebody help with this? I'm not sure which way to normalize to?

> AP: There seems to be a problem here with normalization. Most of the rules for long vowels are declared with \u1427 "canadian syllabics final middle dot", so ᐧᐋ is a sequence of \u1427\140B, but there also appears to be a specific code point for waa: \u1419. I've added a crl_norm.json that normalizes the sequence to the single codepoint for that character and changed the crl_to_ipa.json mapping to use \u1419 instead of \u1427\140B, but I'm not sure if this was the right choice. Either way, there needs to be some sort of normalization step here to handle real world input.

**Comment by dhdaines** [comment]
Hmm.  This looks like a problem that originated in the way the syllabics were entered on the eastcree.org story pages.  Not sure if it has something to do with the input method they used, or some other faulty software.

We should redefine the rules to not have \u1427 in them, but we can also just add a mapping of \u1427 to /w/.

**Comment by roedoejet** [comment]
Thanks @dhdaines !

OK, sounds good. I've emailed Del and sent him the link to this issue so hopefully he can also provide some direction. I don't think we can just straightforwardly map \u1427 to w though, it seems it also maps to labialization (like the superscript one) as in pʷeː

**Comment by deltork** [comment]
This is  a syllabic keyboard input problem. It usually affects all the sequences containing **w**. Such sequences end up being coded with \u1427 + \uXXX . I think the solution will be to provide both the single and double unicode character sequence to the mapping. ie both  \u1419 and \u1427\140B. Alternatively an intermediate step to convert double sequence to the correct single sequence could be added. 
In the real world, people are using syllabic keyboards that still produce the double unicode sequences so the code must make provisions for it one way or another.
This is will apply to almost all the Algonquian family languages that use syllabics .

**Comment by roedoejet** [comment]
OK, this is now fixed, and the mapping goes from crl -> crl-norm by default first (see the flow from crl -> crl-norm -> crl-ipa -> eng-ipa -> eng-arpabet below). The [g2p studio](https://g2p-studio.herokuapp.com/) is also updated with mappings if you want to play around with it. 

![image](https://user-images.githubusercontent.com/14815080/79698077-504b1280-823b-11ea-90cc-ed321ec5b785.png)

**Comment by roedoejet** [comment]
Hm, it looks like there are some bugs that were introduced. For example the input for kʷaː in the `crl_to_ipa.json` was changed from ᐧᑳ to ᑾ, which means that the vowel lengthening was removed right? It looks like the same thing happened with ᐧᐹ and ᑄ for pʷaː and maybe others - Del can you confirm your mapping? See below how normalization happens, but then there is no rule for `ᐧᐹ -> pʷaː` anymore:

![image](https://user-images.githubusercontent.com/14815080/79698289-e29fe600-823c-11ea-8cd8-647bf644dcfa.png)

Also, just fyi, I think it's fine to keep the roman keys (like `"roman": "lwi"`) in the mapping for legibility, but they're not used by the g2p library at all - is that alright? Are they mostly just notes?

**Comment by joanise** [comment]
Just read this whole thread, the idea of going through `crl-norm` is really cool. I can see other cases where spelling is not fully normalized and using this could simplify things for some languages. Just thinking of French accents and Arabic, too, where there are many representations. Having just NFD vs NFC won't always suffice. Anyway, glad you guys found a solution for crl.

**Comment by deltork** [comment]
> Hm, it looks like there are some bugs that were introduced. For example the input for kʷaː in the `crl_to_ipa.json` was changed from ᐧᑳ to ᑾ, which means that the vowel lengthening was removed right? It looks like the same thing happened with ᐧᐹ and ᑄ for pʷaː and maybe others - Del can you confirm your mapping? See below how normalization happens, but then there is no rule for `ᐧᐹ -> pʷaː` anymore:
> 
> ![image](https://user-images.githubusercontent.com/14815080/79698289-e29fe600-823c-11ea-8cd8-647bf644dcfa.png)
> 
I will look over the mapping. 
> Also, just fyi, I think it's fine to keep the roman keys (like `"roman": "lwi"`) in the mapping for legibility, but they're not used by the g2p library at all - is that alright? Are they mostly just notes?

Yes I added the roman field as a note field for us to keep track of the mapping. The library should be ignoring it.

**Comment by roedoejet** [comment]
> Just read this whole thread, the idea of going through `crl-norm` is really cool.

Yea! I thought it was pretty neat it just works. We should probably formalize and document some naming conventions for mappings too based on things like this.

**Comment by deltork** [comment]
I am comparing the mappings to https://www.eastcree.org/syl-keyboard.html

**Comment by roedoejet** [comment]
Great, thanks @deltork - looks good to me.

![image](https://user-images.githubusercontent.com/14815080/79900625-5ec43600-83c3-11ea-8314-b2f8ed6c1f24.png)
