### ISSUE TITLE
version selector doesn't seem to recognize version aliases

### ISSUE THREAD

**Issue by roedoejet** [roedoejet/g2p#341]
I expected toggles for `v2.0.0` and `stable` as well as `latest`

**Comment by joanise** [comment]
Semi fixed, now using the URLs to stable and latest redirects you to v2.0.0 and dev, respectively.

But the selector does not show the aliases.

In an ideal world, I'd want to see this in the selector:
```
v2.0.0 (stable)
dev (latest)
```

Just like https://github.com/squidfunk/mkdocs-material/issues/6436 asks for.

**Comment by joanise** [comment]
Closing this, the aliases work as URLs, and we have no control over displaying the aliases in the selector.
