### ISSUE TITLE
g2p convert added blank line at end. 

### ISSUE THREAD

**Issue by marctessier** [roedoejet/g2p#351]
When I run  `g2p convert ` my output file always has a blank line at end.

Supper annoying, I always have to remember to run `sed -i '$ d' *.gp2` to remove afterwards.

**Comment by joanise** [comment]
@marctessier Let me know if #352 fixes this as you'd like.

**Comment by marctessier** [comment]
Awesome, yes that resolved the issue  . I am not seeing the extra empty  line at end!
