### ISSUE TITLE
English mapping has strange /g/ phoneme

### ISSUE THREAD

**Issue by dhdaines** [roedoejet/g2p#40]
I noticed that "g" was somehow falling through in conversions from oji to eng-arpabet, and couldn't figure out why, until I noticed that the "g" in eng_ipa_to_arpabet.json is not the standard ASCII "g" but actually U+0261 LATIN SMALL LETTER SCRIPT G.

Is there a good reason for this? Should we change it to good old fashioned U+0067 LATIN SMALL LETTER G or should we keep both of them?

**Comment by dhdaines** [comment]
Oh, answered my own question, sort of ... looks like Panphon wants U+0261 and not U+0067...

It would be nice to know the reason for this though!

**Comment by dhdaines** [comment]
Oh, okay, I found it, it's because of "Strict IPA".  Seems bogus to me but whatever.

**Comment by roedoejet** [comment]
I agree it's weird, but panphon doesn't handle U+0067. We should probably note this, and some of the other IPA Unicode peculiarities along with how we handle them (or don't) in the docs. I'm happy to re-open this as a documentation issue.

**Comment by roedoejet** [comment]
Oh oops, on my phone and just read you saw the panphon thing too. Yea it's a bit annoying but I don't think it's going to change, you're right that this is an issue though...

**Comment by roedoejet** [comment]
As of 33ab46d you can run `g2p doctor` which will search mappings for characters in ipa mappings that panphon doesn't recognize. I think in this case, and perhaps others, we should actually catch it before hand, but this could help identify problems. You can run it for specific mappings like so: `g2p doctor -m dan-ipa`

**Comment by roedoejet** [comment]
As of 534e4c1 U+0067 will automatically be converted to U+0261 when generating IPA mappings as well. I think between `g2p doctor` and now this, we can close this issue now. The proper way to add more fallback like this is in the `panphon_preprocessor` mapping in `g2p/mappings/langs/norm/panphon_preprocessor.csv`
