### ISSUE TITLE
Make messages for user errors friendlier in `g2p convert` CLI

### ISSUE THREAD

**Issue by joanise** [roedoejet/g2p#42]
`g2p convert text foo bar` outputs an unnecessary Traceback after outputting an informative error message. Ditto `g2p convert text crl foo`.

`g2p convert text crl crl` outputs a Traceback instead of just saying that's a noop.

`g2p convert text crl fra` outputs two unnecessary Tracebacks after outputting an informative error message.

All of these could follow the sample of `g2p convert text frl`, which outputs an error message and tells the user to call `g2p convert -h` for help.

**Comment by roedoejet** [comment]
Oh, were you going to tackle this? I just saw you assigned yourself. I think exceptions could be handled better in this library (happy to pick this up on Slack), but I added a quick patch that keeps the formatting familiar to the other cli-based exceptions here: d98f65c0a79c9740020e3f3f85c09cd052c3ed0b

**Comment by joanise** [comment]
Hey, even better if you did it already! Thanks!

**Comment by joanise** [comment]
`g2p convert text crl fra` still gets the two tracebacks. Reopening the issue so we don't forget to handle that one better too.

**Comment by roedoejet** [comment]
Whoops, thanks! Fixed here: c7af7ef
