### ISSUE TITLE
Documentation on configuration options

### ISSUE THREAD

**Issue by roedoejet** [roedoejet/g2p#49]
Setting things like `as_is` and `prevent_feeding` properly can be the difference between rules working, and not working. There have been a lot of internal discussions about these things, but we need to document this, along with use cases for when to use each option, and what the defaults are.

**Comment by joanise** [comment]
@roedoejet  I think your hepta-blog covered this. Is that enough to close the issue? Actually, one thing is still needed here: g2p's README.md should have a prominent link to that hepta-blog.

**Comment by roedoejet** [comment]
added with 823672d
