### ISSUE TITLE
g2p doctor issues deprecated warning

### ISSUE THREAD

**Issue by joanise** [roedoejet/g2p#53]
`g2p doctor -m fra` outputs this warning message:

```
/home/joa125/u/anaconda3/envs/ilt/lib/python3.7/site-packages/panphon/distance.py:53: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  dogol_prime = yaml.load(f.read())
```

Investigate and fix, presumably by adding a Loader as indicated in the message, though making sure the fixed code also works with Python 3.6.

**Comment by joanise** [comment]
Bleh, looks like the problem is in panphon, not in our code. @littell are you still in contact with David Mortensen and do you think you could ask him to change line 53 in `panphon/distance.py` to read

    dogol_prime = yaml.load(f.read(), Loader=yaml.FullLoader)

instead of

    dogol_prime = yaml.load(f.read())

This might make panphon incompatible with PyYAML versions older than 5.1, but that was released in 2019, so I'm assuming anyone getting the next version of panphon could also easily get an up-to-date PyYAML.

**Comment by littell** [comment]
Probably easiest to just put it as a new Issue on the PanPhon github; I
know he still keeps up with those.

**Comment by roedoejet** [comment]
Thanks Eric, yes you're right that this is an issue with PanPhon. I made a PR for it here: https://github.com/dmort27/panphon/pull/21
