### ISSUE TITLE
Empty "out" (e.g. for deletion) causes error

### ISSUE THREAD

**Issue by littell** [roedoejet/g2p#7]
An empty string for the "out" in the conversion table (in this case, for a tone-marking letter with no segmental pronunciation) causes a warning (WARNING - Sorry, something went wrong. Try checking the two IOStates objects you're trying to compose) and later an error in alignment, as the word ends up missing from the output table.

**Comment by roedoejet** [comment]
Thanks for finding this. This was actually two separate bugs. One was a smaller issue to do with output delimiters being added erroneously to deleted segments. The other issue was actually a more substantial bug with how composition was (not) working, so this was super helpful. Should be fixed as of e70c3fa480ae2dd8ef976e57fa182a720d7c1512 and release v. 0.12.20190819
